on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        run: |
          curl -sL https://raw.githubusercontent.com/maxatome/install-go/v2.1/install-go.pl |
              perl - tip $HOME/go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
